import type { Metadata } from 'next'
import './globals.css'
import { RyokuchaProvider } from '@ayataka0nk/ryokucha-ui'
import Link from 'next/link'
import '@ayataka0nk/ryokucha-ui/style.css'
import '@/theme.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="light">
        <RyokuchaProvider linkPropName="to" LinkComponent={Link}>
          {children}
        </RyokuchaProvider>
      </body>
    </html>
  )
}
